name = "server_main"
compatibility_date = "2024-07-14"

# [vars]
# MY_VAR = "my-variable"

[vars]
DATABASE_URL= "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTA0NWM4MGItZGE1ZS00MzAxLWExZGMtYWEwZjhiNjY0NGUyIiwidGVuYW50X2lkIjoiYzIzMjliODhhNzhiZjM0MGFiYTliZjgwMjViMzhlNWE4MTliYzRjZjdmYWZlNTYxZTJmMGVlZDMxNDZlYWFkMiIsImludGVybmFsX3NlY3JldCI6IjI2YTJlMGYyLWM4NTgtNDQwZi1iZTQwLTIyMmYzYTg2MDkzYyJ9.T5XAW1K5pQHbzWTiekzx6yefCcEMN0ulSWUAVbtoGYw"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"