name = "server_main"
compatibility_date = "2024-07-14"

# [vars]
# MY_VAR = "my-variable"

[vars]
OPENAI_API_KEY ="sk-proj-2J2u0HczOCBegNNFrlA7T3BlbkFJp8G51CuSoZ32WPnLe7et"

[vars]


[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZTZhYTUzMzYtMDg2MS00NWRhLWEyOWItMjY0MjFjNmE4OTQ5IiwidGVuYW50X2lkIjoiNWZiZDc3YTJmMTQ4NDEyOTM2OGJiOTI4OWQ1ZTQ1ZmQ5YjE2ZDE4MTNlMjkyNTYwNjEzNTc5NzBjM2E1ZGZlZiIsImludGVybmFsX3NlY3JldCI6IjE1NTllYTgwLTExYmQtNGIyZS04ZDRiLWZkYjQwMzUyZDFkZSJ9.zQVaL6_VVYIii9Y-qQ90kH0obI1wDn4Fv_3Ugb8NUXg"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"